### PR TITLE
Add NotoSansDevanagari-Regular-v1

### PR DESCRIPTION
**Pull request by wipfli**
Adds a script that copies all files from "Noto Sans Regular" to "NotoSansDevanagari-Regular-v1" and subsequently downloads glyph ranges located in the private use area from wipfli/pgf-glyph-ranges.

Also commits these glyph ranges directly to the repo.

### CODE REVIEW

**Comment by bdon** [comment]
* There seems to be a convention to use spaces (which get escaped) instead of hyphens or underscores in font names. 
* Is it true that only PUA ranges will ever be used? If so, can we just omit the non-PUA files?

**Comment by wipfli** [comment]
> Is it true that only PUA ranges will ever be used? 

The private use area PUA has roughly 6000 codepoints. Devanagari uses 800. Other scripts like Khmer might use more but I think it should still fit into the PUA.

> If so, can we just omit the non-PUA files?

No, because you might get strings like for example `काठमाडौँ (नेपाल)`, i.e., `Kathmandu (Nepal)`. Here we only use the positioned glyph font for codepoints in the Devanagari script but the whitespace and the opening and closing parenthesis are not part of Devanagari and therefore are not using the PGF codepoints. Similarly, you might run into situations where Devanagari and Latin are mix in which case you will use the bare Unicode for Latin and the encoded codepoints from the PUA for Devanagari.

**Comment by bdon** [comment]
> No, because you might get strings like for example काठमाडौँ (नेपाल), i.e., Kathmandu (Nepal). 

Good catch, then it seems like we are out of luck if a label contains two or more unsupported scripts? Does this happen in only very niche cases?

> bare Unicode for Latin and the encoded codepoints from the PUA for Devanagari.

similarly, could we only contain the Latin/punctuation and PUA parts for these scripts? 

I'm concerned if we have 10+ font stacks, one for each script, we're then managing thousands of files in here.

**Comment by wipfli** [comment]
> Good catch, then it seems like we are out of luck if a label contains two or more unsupported scripts? 

Labels can have multiple unsupported scripts with format expressions and different fontstacks per section. If an osm name tag contains two or more unsupported scripts, it should be cut into parts.

> Does this happen in only very niche cases?

I think so in the case of osm name tags at least. 

> similarly, could we only contain the Latin/punctuation and PUA parts for these scripts?

We could but then maps localized to non-latin scripts like Greek, Cyrillic, Arabic, Hebrew etc could not use PGFs.

I share your concerns about the number of files. Could we use symlinks like `0-255.pbf -> ../Noto Sans Regular/0-255.pbf`?

**Comment by bdon** [comment]
What if we excluded the Han range in the BMP? Clients should use localIdeographs anyways.

**Comment by bdon** [comment]
I think symlinks are a reasonable solution, too. I just tested that they work with GitHub pages:

https://github.com/bdon/protomaps-workshop-sotmus24/blob/main/utah_basemap2.pmtiles
pages URL: https://bdon.github.io/protomaps-workshop-sotmus24/utah_basemap2.pmtiles

**Comment by wipfli** [comment]
If the symlinks work that would be my preferred option. You are right that CJK accounts for maybe 50% of all BMP codepoints, but then you would still be left 128 glyph ranges instead of 256 glyph ranges. And I know of users who prefer the visual quality of server-rendered CJK over the tinysdf ones...

**Comment by bdon** [comment]
Closing in favor of #6

**Pull request closed without merging**
